pub const ErrorCode = enum(c_int) {
    ok = 0,
    cancelled = 1,
    unknown = 2,
    invalid_argument = 3,
    deadline_exceeded = 4,
    not_found = 5,
    already_exists = 6,
    permission_denied = 7,
    resource_exhausted = 8,
    failed_precondition = 9,
    aborted = 10,
    out_of_range = 11,
    unimplemented = 12,
    internal = 13,
    unavailable = 14,
    data_loss = 15,
    unauthenticated = 16,
};

pub const BufferType = enum(c_int) {
    invalid = 0,
    pred = 1,
    s8 = 2,
    s16 = 3,
    s32 = 4,
    s64 = 5,
    u8 = 6,
    u16 = 7,
    u32 = 8,
    u64 = 9,
    f16 = 10,
    f32 = 11,
    f64 = 12,
    bf16 = 13,
    c64 = 14,
    c128 = 15,
    f8e5m2 = 16,
    f8e4m3fn = 17,
    f8e4m3b11fnuz = 18,
    f8e5m2fnuz = 19,
    f8e4m3fnuz = 20,
    s4 = 21,
    u4 = 22,
    token = 23,
    s2 = 24,
    u2 = 25,
    f8e4m3 = 26,
    f8e3m4 = 27,
    f8e8m0fnu = 28,
    f4e2m1fn = 29,
    s1 = 30,
    u1 = 31,
};

pub const HostBufferSemantics = enum(c_int) {
    immutable_only_during_call = 0,
    immutable_until_transfer_completes = 1,
    immutable_zero_copy = 2,
    mutable_zero_copy = 3,
};

pub const NamedValueType = enum(c_int) {
    string = 0,
    int64 = 1,
    int64_list = 2,
    float = 3,
    bool = 4,
};

pub const ExtensionType = enum(c_int) {
    gpu_custom_call = 0,
    profiler = 1,
    custom_partitioner = 2,
    stream = 3,
    layouts = 4,
    ffi = 5,
    memory_descriptions = 6,
    triton = 7,
    raw_buffer = 8,
    phase_compile = 9,
    example = 10,
    unknown = 11,
    cross_host_transfers = 12,
    executable_metadata = 13,
    callback = 14,
    host_allocator = 15,
    tpu_topology = 16,
    tpu_executable = 17,
    megascale = 18,
    shardings = 19,
    abi_version = 20,
    collectives = 21,
    multi_slice = 22,
    host_memory_allocator = 23,
    xla_transform = 24,
};

pub const BufferMemoryLayoutType = enum(c_int) {
    tiled = 0,
    strides = 1,
};

pub const ProcessState = enum(c_int) {
    unspecified = 0,
    uninitialized = 1,
    disconnected = 2,
    connected = 3,
    @"error" = 4,
    _,
};
